### ISSUE TITLE
`--main` invalid argument and throws AIOB exception

### ISSUE THREAD

**Issue by manikmagar** [mulesoft-labs/data-weave-cli#25]
**Describe the bug**

Trying to run a mapping file from jar -

```
❯ dw --path ~/dev/sample.jar  --main "Test.dwl"
[ERROR] Parameters configuration error:
[ERROR] Invalid argument --main
```

Looks like code has it `-main` instead of `--main`, see [here](https://github.com/mulesoft-labs/data-weave-cli/blob/master/native-cli/src/main/scala/org/mule/weave/dwnative/cli/CLIArgumentsParser.scala#L222).

When using `-main`, it results in this error -

```
❯ dw --path ~/dev/sample.jar  -main "Test.dwl"
[ERROR] Unexpected exception happened while executing command. Please report this as an issue in https://github.com/mulesoft-labs/data-weave-cli/issues with all the details to reproduce.
Stacktrace is: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at org.mule.weave.dwnative.cli.CLIArgumentsParser.$anonfun$parse$3(CLIArgumentsParser.scala:226)
	at org.mule.weave.dwnative.cli.commands.RunWeaveCommand.doRun(RunWeaveCommand.scala:89)
	at org.mule.weave.dwnative.cli.commands.RunWeaveCommand.exec(RunWeaveCommand.scala:56)
	at org.mule.weave.dwnative.cli.DataWeaveCLIRunner.run(DataWeaveCLI.scala:30)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$.delayedEndpoint$org$mule$weave$dwnative$cli$DataWeaveCLI$1(DataWeaveCLI.scala:11)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$delayedInit$body.apply(DataWeaveCLI.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at org.mule.weave.dwnative.cli.DataWeaveCLI$.main(DataWeaveCLI.scala:9)
	at org.mule.weave.dwnative.cli.DataWeaveCLI.main(DataWeaveCLI.scala)

```

It can be reproduced by simply running `dw -main "Test.dwl"`.

**Comment by machaval** [comment]
Thanks for reporting this we will take a look at it.

**Comment by machaval** [comment]
This issue is going to be fixed on next release. Thanks for reporting

**Comment by machaval** [comment]
Please run `brew upgrade`

**Comment by mmagar-rh** [comment]
@machaval Can this be released for Windows version too? I see the link on Readme is pointing to an old release.

**Comment by machaval** [comment]
Yes Readme points to an old one. Windows build is being done by hand and I was able to do it when I got my machine. But sadly I return it :( I will try to build a new one when I have it
